config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  get 'archive/index'
  get 'locales/change', as: 'change_locale'

  resources :disciplines
  resources :semesters
  resources :visits, only: [:create, :destroy, :show, :update] do
    resources :homeworks
    member do
      get 'result'
      post 'update_created_at'
    end
  end
  resources :homeworks, only: [:create, :destroy, :show, :update]
  resources :relationships, only: [:create, :destroy, :show] do
    member do
      post 'update_proportions'
      get 'total'
    end
    resources :discipline_modules, only: [:index]
  end
  resources :discipline_modules do
    member do
      get 'generate_tickets'
      post 'do_generate_tickets'
    end
  end
  resources :attends, only: [:create, :update] do
    member do
      post 'update_mark'
      post 'update_title'
    end
  end
  resources :groups do
    member do
      delete 'remove_user'
      post   'add_user'
      get    'search_user'
    end
  end
  resources :student_modules, only: [:show, :destroy] do
    member do
      post 'update_answer_result'
      post 'check_answers'
      get  'finish_check'
      get  'copy_result'
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users do
    collection do
      post 'create_manual'
    end
  end

  namespace :api do
    namespace :v1 do
      post 'sign_in' => 'users#sign_in'
      get  'relationships/current' => 'relationships#current'
      get  'relationships/:relationship_id/modules' => 'visits#get_modules'
      get  'relationships/:relationship_id/modules/:id' => 'student_modules#show'
      post 'relationships/:relationship_id/modules/:id/questions/:question_id/answer' => 'student_modules#answer'
      post 'relationships/:relationship_id/modules/:id/finish' => 'student_modules#finish'

      get  'disciplines/:discipline_id/modules' => 'discipline_modules#index'
      post 'disciplines/:discipline_id/modules' => 'discipline_modules#create'
      get 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#show'
      post 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#update'
      delete 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#delete'

      get  'modules/:discipline_module_id/question_groups' => 'question_groups#index'
      post 'modules/:discipline_module_id/question_groups' => 'question_groups#create'
      get  'modules/:discipline_module_id/question_groups/:id' => 'question_groups#show'
      post 'modules/:discipline_module_id/question_groups/:id' => 'question_groups#update'
      delete 'modules/:discipline_module_id/question_groups/:id' => 'question_groups#delete'
      
      get  'question_groups/:question_group_id/questions' => 'questions#index'
      post 'question_groups/:question_group_id/questions' => 'questions#create'
      post 'question_groups/:question_group_id/questions/:id' => 'questions#update'
      delete 'question_groups/:question_group_id/questions/:id' => 'questions#delete'

      get  'disciplines' => 'disciplines#index'
    end
  end
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  belongs_to :user
  has_many :relationships, dependent: :destroy
  has_many :discipline_modules, dependent: :destroy

  default_scope { order 'title' }

  validates :title, presence: true
end

app/controllers/api/v1/disciplines_controller.rb
class Api::V1::DisciplinesController < Api::ApiController
  def index
    result = Discipline::List.(params: params, current_user: current_user)
    
    if result.success?
      render_ok_json(Api::V1::Discipline::Representer.for_collection.new(result[:models]))
    else
      render_request_error_json(result[:error_msg])
    end
  end
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  include ApplicationHelper
  before_action :set_discipline, :owner_or_admin, only: [:show, :edit, :update, :destroy]
  before_action AdminOrTeacherActionCallback

  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = current_user.allowed_disciplines.paginate(page: params[:page], per_page: PER_PAGE)
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
    unless params[:semester_id].nil?
      @semester = Semester.find(params[:semester_id])
    else
      @semester = Semester.current
    end
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    if current_user.admin?
      @discipline = Discipline.new(discipline_params)
    else
      @discipline = current_user.disciplines.build(discipline_params)
    end

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_discipline
    @discipline = Discipline.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def discipline_params
    if current_user.admin?
      params.require(:discipline).permit(:title, :user_id)
    else
      params.require(:discipline).permit(:title)
    end
  end

  def owner_or_admin
    unless current_user.admin? || current_user.id == @discipline.user_id
      redirect_to :root, :alert => 'Access denied.'
    end
  end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.erb
<div class="row">
<%= form_for(@discipline, html: {class: 'form-horizontal col-md-3 col-md-offset-1'}) do |f| %>
  <% if @discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% @discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <div class="row">
        <div class="input-field col s12 m6">
          <%= f.text_field :title, :autofocus => true %>
          <%= f.label t(:title) %>
        </div>
        <div class="input-field col s12 m6">
          <% if current_user.admin? %>
            <%= f.collection_select(:user_id, User.teacher, :id, :name) if current_user.admin? %>
            <%= f.label t(:teacher) %>
          <% end %>
        </div>
      </div>

      <%= button_tag t(:save), class: 'btn waves-effect waves-light', type: 'submit' %>
<% end %>
</div>

app/views/disciplines/_semester_form.html.erb
<%= form_tag(discipline_path(discipline), class: 'form-inline', method: :get, id: 'filter-disciplines-form') do %>
    <div class="card hoverable">
      <div class="card-content">
        <span class="card-title black-text"><%= t(:semester) %></span>
        <p>
          <%= select_tag 'semester_id', options_from_collection_for_select(Semester.all, 'id', 'name', semester.present? ? semester.id : nil), {class: 'form-control'} %>
        </p>
      </div>
      <div class="card-action">
        <%= link_to t(:show), '', onclick: '$("#filter-disciplines-form").submit(); return false;' %>
      </div>
    </div>
<% end %>

app/views/disciplines/edit.html.erb
<div class="card hoverable">
  <div class="card-content">
    <span class="card-title black-text"><%= t(:edit) %> <%= t(:discipline) %></span>
  </div>
</div>

<%= render 'form' %>

<%= link_to t(:show), @discipline, class: 'btn btn-flat waves-effect waves-teal' %>
<%= link_to t(:back), disciplines_path, class: 'btn btn-flat waves-effect waves-teal' %>

app/views/disciplines/index.html.erb
<div class="card hoverable">
  <div class="card-content">
    <span class="card-title black-text"><%= t(:disciplines) %></span>
    <p>
      <%= link_to t(:new) + ' ' + t(:discipline), new_discipline_path, class: 'btn waves-effect waves-light' %>
    </p>
  </div>
</div>

<table class="striped">
  <thead>
    <tr>
      <th><%= t(:title) %></th>
      <th><%= t(:teacher) %></th>
      <th><%= t(:actions) %></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= discipline.title %></td>
        <td><%= discipline.user.name %></td>
        <td>
          <%= link_to raw('<i class="fa fa-eye"></i>'), discipline, title: t(:show) %>
          <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_discipline_path(discipline), title: t(:edit) %>
          <%= link_to raw('<i class="fa fa-trash"></i>'), discipline, method: :delete, data: {confirm: t(:are_you_sure)}, title: t(:delete) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

app/views/disciplines/new.html.erb
<div class="card hoverable">
  <div class="card-content">
    <span class="card-title black-text"><%= t(:new) %> <%= t(:discipline) %></span>
  </div>
</div>

<%= render 'form' %>

<%= link_to t(:back), disciplines_path, class: 'btn btn-flat waves-effect waves-teal' %>

app/views/disciplines/show.html.erb
<div class="card hoverable">
  <div class="card-content">
    <span class="card-title black-text"><%= @discipline.title %></span>

    <p>
      <strong><%= t(:teacher) %>:</strong>
      <%= gravatar_for @discipline.user %>
      <%= @discipline.user.name %>
    </p>
  </div>
  <div class="card-action">
    <%= link_to t(:edit), edit_discipline_path(@discipline) %>
    <%= link_to t(:back), disciplines_path %>
  </div>
</div>

<div class="row">
  <div class="col m4 s12">
    <%= render 'semester_form', discipline: @discipline, semester: @semester %>
  </div>
  <div class="col m8 s12">
    <ul class="collection with-header">
      <li class="collection-header">
        <h4><%= t(:groups) %>
          <small>
            <%= link_to raw('<i class="material-icons">add</i>'), semester_path(current_semester), class: 'btn-floating waves-effect waves-light red', title: t(:add_new_group_to_discipline) unless current_semester.nil? %>
          </small>
        </h4>
      </li>
      <% if @semester.present? %>
          <% @semester.relationships.filter_discipline(@discipline).each do |relationship| %>
              <li class="collection-item">
                <div>
                  <%= link_to relationship.group.title + ' (' + relationship.group.year.to_s + ')', relationship.group %>

                  <%= link_to t(:marks), relationship_path(relationship), class: 'secondary-content' %>
                </div>
              </li>
          <% end %>
      <% end %>
    </ul>
  </div>
</div>