config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  get 'archive/index'
  get 'locales/change', as: 'change_locale'

  resources :disciplines
  resources :semesters
  resources :visits, only: [:create, :destroy, :show, :update] do
    resources :homeworks
    member do
      get 'result'
      post 'update_created_at'
    end
  end
  resources :homeworks, only: [:create, :destroy, :show, :update]
  resources :relationships, only: [:create, :destroy, :show] do
    member do
      post 'update_proportions'
      get 'total'
    end
    resources :discipline_modules, only: [:index]
  end
  resources :discipline_modules do
    member do
      get 'generate_tickets'
      post 'do_generate_tickets'
    end
  end
  resources :attends, only: [:create, :update] do
    member do
      post 'update_mark'
      post 'update_title'
    end
  end
  resources :groups do
    member do
      delete 'remove_user'
      post   'add_user'
      get    'search_user'
    end
  end
  resources :student_modules, only: [:show, :destroy] do
    member do
      post 'update_answer_result'
      post 'check_answers'
      get  'finish_check'
      get  'copy_result'
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users do
    collection do
      post 'create_manual'
    end
  end

  namespace :api do
    namespace :v1 do
      post 'sign_in' => 'users#sign_in'
      get  'relationships/current' => 'relationships#current'
      get  'relationships/:relationship_id/modules' => 'visits#get_modules'
      get  'relationships/:relationship_id/modules/:id' => 'student_modules#show'
      post 'relationships/:relationship_id/modules/:id/questions/:question_id/answer' => 'student_modules#answer'
      post 'relationships/:relationship_id/modules/:id/finish' => 'student_modules#finish'

      get  'disciplines/:discipline_id/modules' => 'discipline_modules#index'
      post 'disciplines/:discipline_id/modules' => 'discipline_modules#create'
      get 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#show'
      post 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#update'
      delete 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#delete'

      get  'modules/:discipline_module_id/question_groups' => 'question_groups#index'
      post 'modules/:discipline_module_id/question_groups' => 'question_groups#create'
      get  'modules/:discipline_module_id/question_groups/:id' => 'question_groups#show'
      post 'modules/:discipline_module_id/question_groups/:id' => 'question_groups#update'
      delete 'modules/:discipline_module_id/question_groups/:id' => 'question_groups#delete'
      
      get  'question_groups/:question_group_id/questions' => 'questions#index'
      post 'question_groups/:question_group_id/questions' => 'questions#create'
      post 'question_groups/:question_group_id/questions/:id' => 'questions#update'
      delete 'question_groups/:question_group_id/questions/:id' => 'questions#delete'

      get  'disciplines' => 'disciplines#index'
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    if user_signed_in? && Semester.current.present?
      @relationships = Relationship.where(discipline: current_user.disciplines.map {|d| d.id}).where(semester: Semester.current)
      if current_user.student?
        @homeworks = current_user.homeworks.joins(visit: [relationship: :discipline])
                          .where('relationships.semester_id = ?', Semester.current.id)
                          .where('homeworks.body != \'\'')
                          .order('homeworks.created_at desc')
      else
        @homeworks = Homework.joins(visit: [relationship: :discipline])
                          .where('relationships.semester_id = ?', Semester.current.id)
                          .where('homeworks.body is NULL')
                          .where('disciplines.id IN (?)', current_user.disciplines.select('id'))
                          .order('homeworks.created_at desc')
      end
    else
      @relationships = []
      @homeworks = []
    end
  end
end

app/views/visitors/_student.html.erb
<div class="row">

  <div class="col s12 m6">
    <h4><%=t(:disciplines)%></h4>
    <ul class="collapsible popout" data-collapsible="accordion">
      <% current_user.groups.sort_by(&:year).reverse.each do |group| %>
          <li>
            <div class="collapsible-header <%= group.year == Time.now.year ? 'active' : '' %>">
              <%= group.year %>
            </div>
            <div class="collapsible-body">
              <p>
                <% group.relationships.each do |rel| %>
                    <%= link_to rel.discipline.title, relationship_path(rel) %><br />
                <% end %>
              </p>
            </div>
          </li>
      <% end %>
    </ul>
  </div>

  <div class="col s12 m6">
    <h4><%=t(:homeworks)%></h4>
      <% @homeworks.to_a.uniq(&:visit_id).each do |h| %>
        <div class="card">
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">
              <%= h.visit.relationship.discipline.title %>
              <i class="material-icons right">more_vert</i>
            </span>
            <p><%= link_to t(:view), visit_homeworks_path(visit_id: h.visit_id, user_id: current_user.id) %> | <%= h.updated_at %></p>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><%= h.visit.relationship.discipline.title %><i class="material-icons right">close</i></span>
            <p><%= simple_format(h.body) %></p>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/visitors/_teacher.html.erb
<div class="row">

  <div class="col s12 m6">
    <h4><%=t(:semester)%></h4>
    <div class="card">
      <div class="card-content">
        <span class="card-title black-text"><%= current_semester.nil? ? t(:no_semester_in_current_year) : (t(:current) + ' ' + t(:semester)) %></span>
        <p>
          <% if current_semester.nil? %>
              <%= link_to t(:create) + ' ' + t(:semester), new_semester_path, class: 'btn btn-success' -%>
          <% else %>
              <%= link_to current_semester.name, semester_path(current_semester) -%>
          <% end %>
        </p>
      </div>
    </div>

    <% if (!@relationships.empty?) %>
        <div class="card">
          <div class="card-content">
            <span class="card-title black-text"><%= t :disciplines %></span>
            <p>
              <% @relationships.each do |r| %>
                  <%= link_to r.discipline.title << ' (' << r.group.title << ')', relationship_path(r) %> <br/>
              <% end %>
            </p>
          </div>
        </div>
    <% end %>
  </div>

  <div class="col s12 m6">
    <h4><%=t(:homeworks)%></h4>
    <ul class="collapsible popout" data-collapsible="accordion">
      <% @homeworks.to_a.uniq { |h| [h.visit_id, h.user_id] }.each do |h| %>
          <li>
            <div class="collapsible-header">
              <%= h.user.name %> (<%= h.visit.relationship.group.title %>)
            </div>
            <div class="collapsible-body">
              <p>
                <%= h.visit.relationship.discipline.title %> <br />
                <%= h.comment_text %> <br />
                [<%= h.created_at %>] |
                    <%= link_to t(:view), visit_homeworks_path(visit_id: h.visit_id, user_id: h.user_id) %>
              </p>
            </div>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/visitors/_welcome.html.erb
<div class="row">
  <div class="col s12 offset-m3 m6">
    <div class="card hoverable">
      <div class="card-content">
        <span class="card-title black-text"><%= t :welcome %></span>
        <p>
          <%= t :please %> <%= t(:press) %> "<%= t(:sign_in) %>"<%= t(:to_view_journal)%>.
        </p>
      </div>
      <div class="card-action">
        <%= link_to t(:sign_in), new_user_session_path %>
      </div>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<% if(user_signed_in?) %>
    <% if !current_user.student? %>
        <%= render 'teacher' %>
    <% else %>
        <%= render 'student' %>
    <% end %>
<% else %>
    <%= render 'welcome' %>
<% end %>