config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  get 'archive/index'
  get 'locales/change', as: 'change_locale'

  resources :disciplines
  resources :semesters
  resources :visits, only: [:create, :destroy, :show, :update] do
    resources :homeworks
    member do
      get 'result'
      post 'update_created_at'
    end
  end
  resources :homeworks, only: [:create, :destroy, :show, :update]
  resources :relationships, only: [:create, :destroy, :show] do
    member do
      post 'update_proportions'
      get 'total'
    end
    resources :discipline_modules, only: [:index]
  end
  resources :discipline_modules do
    member do
      get 'generate_tickets'
      post 'do_generate_tickets'
    end
  end
  resources :attends, only: [:create, :update] do
    member do
      post 'update_mark'
      post 'update_title'
    end
  end
  resources :groups do
    member do
      delete 'remove_user'
      post   'add_user'
      get    'search_user'
    end
  end
  resources :student_modules, only: [:show, :destroy] do
    member do
      post 'update_answer_result'
      post 'check_answers'
      get  'finish_check'
      get  'copy_result'
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users do
    collection do
      post 'create_manual'
    end
  end

  namespace :api do
    namespace :v1 do
      post 'sign_in' => 'users#sign_in'
      get  'relationships/current' => 'relationships#current'
      get  'relationships/:relationship_id/modules' => 'visits#get_modules'
      get  'relationships/:relationship_id/modules/:id' => 'student_modules#show'
      post 'relationships/:relationship_id/modules/:id/questions/:question_id/answer' => 'student_modules#answer'
      post 'relationships/:relationship_id/modules/:id/finish' => 'student_modules#finish'

      get  'disciplines/:discipline_id/modules' => 'discipline_modules#index'
      post 'disciplines/:discipline_id/modules' => 'discipline_modules#create'
      get 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#show'
      post 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#update'
      delete 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#delete'

      get  'modules/:discipline_module_id/question_groups' => 'question_groups#index'
      post 'modules/:discipline_module_id/question_groups' => 'question_groups#create'
      get  'modules/:discipline_module_id/question_groups/:id' => 'question_groups#show'
      post 'modules/:discipline_module_id/question_groups/:id' => 'question_groups#update'
      delete 'modules/:discipline_module_id/question_groups/:id' => 'question_groups#delete'
      
      get  'question_groups/:question_group_id/questions' => 'questions#index'
      post 'question_groups/:question_group_id/questions' => 'questions#create'
      post 'question_groups/:question_group_id/questions/:id' => 'questions#update'
      delete 'question_groups/:question_group_id/questions/:id' => 'questions#delete'

      get  'disciplines' => 'disciplines#index'
    end
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  serialize :proportions
  scope :filter_discipline, ->(discipline) { where("discipline_id = ?", discipline.id) }

  belongs_to :semester
  belongs_to :discipline
  belongs_to :group
  has_many :visits, dependent: :destroy

  validates_uniqueness_of :group_id, scope: [:discipline_id, :semester_id], message: ' and discipline are already in semester'
end

app/controllers/api/v1/relationships_controller.rb
class Api::V1::RelationshipsController < Api::ApiController
  def current
    result = Relationship::GetCurrent.(params: {}, current_user: current_user)
    
    if result.success?
      render_ok_json(Api::V1::Relationship::Representer.for_collection.new(result[:relationships]))
    else
      render_request_error_json(result[:error_msg])
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: [:show, :destroy, :update_proportions, :total]
  before_action AdminOrTeacherActionCallback, except: [:show, :total]
  before_action

  def show
    params[:kind] = :lab if params[:kind].nil?
    @attends = Attend.where(visit_id: @relationship.visits.all).where(user_id: @relationship.group.users.all).all
  end

  def total
    @attends = Attend.where(visit_id: @relationship.visits.all).where(user_id: @relationship.group.users.all).all
    render partial: 'total', locals: { relationship: @relationship }
  end

  def create
    @relationship = Relationship.new(relationship_params)
    if owner_or_admin(@relationship.discipline) && @relationship.save
      redirect_back fallback_location: root_path, notice: 'Group was added to semester!'
    else
      if (!owner_or_admin(@relationship.discipline))
        redirect_back fallback_location: root_path, alert: 'Access denied!'
      else
        redirect_back fallback_location: root_path, alert: @relationship.errors.full_messages.join(". ")
      end
    end
  end

  def destroy
    if owner_or_admin(@relationship.discipline)
      @relationship.destroy
      redirect_back fallback_location: root_path, notice: 'Group was deleted from semester!'
    else
      redirect_back fallback_location: root_path, alert: 'Access denied!'
    end
  end

  def update_proportions
    @relationship.proportions = params[:total]
    if @relationship.save
      redirect_to relationship_path(@relationship, kind: :total), notice: 'Total is saved!'
    else
      redirect_to relationship_path(@relationship, kind: :total), alert: 'Total is NOT saved!'
    end
  end

  private

  def set_relationship
    @relationship = Relationship.find(params[:id])
  end

  def relationship_params
    params.require(:relationship).permit(:semester_id, :discipline_id, :group_id)
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
  def mark_by_total(total)
    case total
      when 90..101
        '5'
      when 75..90
        '4'
      when 60..75
        '3'
      else
        '2'
    end
  end

  def ects_by_total(total)
    case total
      when 90..101
        'A'
      when 83..90
        'B'
      when 75..83
        'C'
      when 68..75
        'D'
      when 60..68
        'E'
      when 35..60
        'FX'
      else
        'F'
    end
  end

  def cache_key_for_relationship(relationship)
    semester = relationship.semester
    discipline = relationship.discipline
    group = relationship.group
    "relationship/#{relationship.id}-#{relationship.updated_at}-#{semester.id}-#{semester.updated_at}-#{discipline.id}-#{discipline.updated_at}-#{group.id}-#{group.updated_at}-#{I18n.locale}-#{current_user.id}-#{params[:kind]}"
  end
end

app/views/relationships/_attend_form.html.erb
<% if !current_user.student? %>
    <%= form_for(visit.attends.build(user_id: student.id), remote: true) do |f| %>
        <%= f.hidden_field :user_id %>
        <%= f.hidden_field :visit_id %>
        <%= f.hidden_field :presence, value: 'present' %>
        <%= link_to '-', '#', :onclick=>'$(this).parent().submit(); return false;' %>
    <% end %>
<% else %>
    -
<% end %>

app/views/relationships/_attend_toggle.html.erb
<%= form_for(attend, remote: true) do |f| %>
    <% if attend.present? %>
        <%= f.hidden_field :presence, value: 'absent' %>
        <% if !current_user.student? %>
            <%= link_to '*', '#', :onclick=>'$(this).parent().submit(); return false;' %>
        <% else %>
            *
        <% end %>
    <% elsif attend.absent? %>
        <%= f.hidden_field :presence, value: 'late' %>
        <% if !current_user.student? %>
            <%= link_to 'H', '#', :onclick=>'$(this).parent().submit(); return false;' %>
        <% else %>
            H
        <% end %>
    <% elsif attend.late? %>
        <%= f.hidden_field :presence, value: 'present' %>
        <% if !current_user.student? %>
            <%= link_to 'оп', '#', :onclick=>'$(this).parent().submit(); return false;' %>
        <% else %>
            оп
        <% end %>
    <% end %>
<% end %>

app/views/relationships/_mark_form.html.erb
<% if !current_user.student? %>
    <%= form_for(attend, url: update_mark_attend_path(attend), remote: true, method: :post) do |f| %>
        <%= f.text_field :mark, :onblur => '$(this).parent().submit(); return false;', value: (attend.mark==0)?'': "%g" % ("%.1f" % attend.mark)  %>
    <% end %>
<% else %>
    <%= (attend.mark==0)?'':attend.mark %>
<% end %>

app/views/relationships/_total.html.erb
<div class="row" id="total-cont">
  <% if !current_user.student? %>
  <div class="col s12 m2">
    <%= form_tag(update_proportions_relationship_path(relationship), method: :post, html: {class: 'form-horizontal total-form'}) do |f| %>

        <% Visit.kinds.each do |kind, index| %>
              <%
                 value = (relationship.proportions.nil?) ? 0 : relationship.proportions["#{kind.to_s}_per_each".to_sym].gsub(/\D/, '').to_i
              %>
            <div class="input-field">
                <%= number_field_tag 'total['+kind.to_s+'_per_each]',  value %>
                <%= label_tag 'Per '+kind.to_s%>
            </div>
        <% end %>
          <% Visit.kinds.each do |kind, index| %>
              <%
                 value = (relationship.proportions.nil?) ? 0 : relationship.proportions["#{kind.to_s}_total".to_sym].gsub(/\D/, '').to_i
              %>
            <div class="input-field">
              <%= number_field_tag 'total['+kind.to_s+'_total]', value %>
              <%= label_tag 'Total '+kind.to_s %>
            </div>
          <% end %>
        <%= button_tag t(:save), class: 'btn waves-effect waves-light', type: 'submit' %>
    <% end %>
  </div>
  <% end %>
  <div class="col s12 m10">
    <table class="visits">
      <thead>
      <tr>
        <th class="delimiter"><%= t(:student) %></th>
        <% Visit.kinds.each do |kind, index| %>
            <th class="delimiter"><%= t(kind.to_s.pluralize.downcase) %></th>
        <% end %>
        <th class="delimiter"><%= t(:total) %></th>
        <th class="delimiter"><%= t(:mark) %></th>
        <th class="delimiter">ECTS</th>
      </tr>
      </thead>
      <% relationship.group.users.each do |student| %>
          <% student_total = 0 %>
          <tr>
            <th class="delimiter"><%= student.name %></th>
            <% Visit.kinds.each do |kind, index| %>
                <%
                   attends = @attends.select { |attend| attend.user_id == student.id and attend.relationship_id == relationship.id and attend.kind == index }
                   sum = attends.map(&:mark).inject(0, &:+)
                   num = relationship.visits.send(kind).size
                   total = (relationship.proportions.nil?) ? 0 : relationship.proportions["#{kind.to_s}_total".to_sym].gsub(/\D/, '').to_i
                   per_each = (relationship.proportions.nil?) ? 0 : relationship.proportions["#{kind.to_s}_per_each".to_sym].gsub(/\D/, '').to_i
                   kind_total = (relationship.proportions.nil?) ? 0 : (total.to_f*sum.to_f).to_f / (per_each.to_f * num.to_f).to_f
                   kind_total = 0 if total == 0 || per_each == 0 || kind_total.nan?
                   student_total += kind_total
                %>
                <td class="delimiter"> <%= "%g" % ("%.1f" % kind_total) %> </td>
            <% end %>
            <td class="delimiter mark<%= mark_by_total(student_total) %>"> <%= "%g" % ("%.1f" % student_total) %> </td>
            <td class="delimiter mark<%= mark_by_total(student_total) %>"> <%= mark_by_total(student_total) %> </td>
            <td class="delimiter mark<%= mark_by_total(student_total) %>"> <%= ects_by_total(student_total) %> </td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/relationships/_visit.html.erb
<% attend = @attends.select { |attend| attend.visit_id == visit.id and attend.user_id == student.id }[0] %>
<td id="attend-presence-<%= student.id %>-<%= visit.id %>" class="presence">
<% if attend.nil? %>
  <%= render 'attend_form', visit: visit, student: student %>
<% else %>
  <%= render 'attend_toggle', attend: attend %>
<% end %>
</td>
<td id="attend-mark-<%= student.id %>-<%= visit.id %>" class="delimiter mark">
  <% if attend.nil? %>
      -
  <% else %>
    <%= render 'mark_form', attend: attend  %>
  <% end %>
  <% if visit.kind.to_s == 'homework' && (current_user.id == student.id || !current_user.student?) && !attend.nil? %>
      <%= link_to fa_icon('eye') + ' ' + attend.title, visit_homeworks_path(visit_id: visit.id, user_id: student.id), class: 'view-attend' %>
  <% elsif visit.kind.to_s == 'homework' && !attend.nil? && current_user.student?%>
      <%= attend.title %>
  <% end %>
</td>

app/views/relationships/_visit_date_form.html.erb
<% if !current_user.student? %>
    <%= form_for(visit, url: update_created_at_visit_path(visit), remote: true, method: :post, html: {id: "visit-date-#{visit.id}"}) do |f| %>
        <%= f.text_field :created_at, :onblur => '$(this).parent().submit(); return false;', value: visit.created_at.strftime('%d.%m') %>
    <% end %>
<% else %>
    <%= visit.created_at.strftime('%d.%m') %>
<% end %>

app/views/relationships/_visit_form.html.erb
<% if !current_user.student? %>
    <%= form_for(visit, remote: true, method: :patch) do |f| %>
        <%= f.text_field :title, :onblur => '$(this).parent().submit(); return false;' %>
    <% end %>
<% else %>
    <%= visit.title %>
<% end %>

app/views/relationships/_visits.html.erb
<div class="row">
  <% if !current_user.student? %>
      <div class="col s8 m8">
        <%= form_for(@relationship.visits.build, html: {class: 'form-horizontal'}) do |f| %>
            <div class="row">
              <div class="input-field col m4">
                <%= f.text_field :title %>
                <%= f.label t(:title) %>
              </div>
              <%= f.hidden_field :relationship_id %>
              <%= f.hidden_field :kind, {value: kind} %>
              <div class="input-field col m8">
                <%= f.submit t(:add), class: 'btn btn-success' %>
              </div>
            </div>
        <% end %>
      </div>
  <% end %>
  <div class="col s12 m12">
    <table class="visits <%= kind %> hoverable">
      <thead>
      <tr>
        <th class="delimiter student-name"><%= t(:student) %></th>
        <% @relationship.visits.send(kind).each do |visit| %>
            <th colspan="2" class="delimiter" id="visit-<%= visit.id %>">
              <%= render 'visit_form', visit: visit %>
            </th>
        <% end %>
      </tr>
      </thead>
      <% @relationship.group.users.each_with_index do |student, i| %>
          <tr>
            <th class="delimiter student-name"><%= link_to "#{i+1}. " + student.name, user_path(student), target: "_blank" %></th>
            <% @relationship.visits.send(kind).each do |visit| %>
                <%= render 'visit', visit: visit, student: student %>
            <% end %>
          </tr>
      <% end %>
      <tr>
        <td class="delimiter"><b><%= t(:rdate) %>:</b></td>
        <% @relationship.visits.send(kind).each do |visit| %>
            <td colspan="2" class="delimiter">
              <%= render 'visit_date_form', visit: visit %>
            </td>
        <% end %>
      </tr>
      <% if !current_user.student? %>
          <tr>
            <td class="delimiter"><b>Remove:</b></td>
            <% @relationship.visits.send(kind).each do |visit| %>
                <td colspan="2" class="delimiter">
                  <%= link_to 'x', visit, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
                </td>
            <% end %>
          </tr>
      <% end %>
    </table>
  </div>

</div>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/relationships/show.html.erb
<% cache(cache_key_for_relationship(@relationship)) do %>
    <div class="card hoverable">
      <div class="card-content">
        <span class="card-title black-text"><%= @relationship.discipline.title %></span>

        <p>
          <%= t(:teacher) %> <%= @relationship.discipline.user.name %> <br/>
          <%= t(:group) %> <%= @relationship.group.title %>, <%= @relationship.semester.name %>
        </p>
      </div>
      <% if !current_user.student? %>
        <div class="card-action">
          <a href="<%= relationship_discipline_modules_path(@relationship) %>"><%= t(:online_modules) %></a>
        </div>
      <% end %>
    </div>

    <div class="row">

      <!-- Nav tabs -->
      <div class="col s12">
        <ul class="tabs">
          <% Visit.kinds.each do |kind, index| %>
              <li class="tab col">
                <a href="#<%= kind.to_s.pluralize %>" <%= 'class=active' if kind == params[:kind] %>><%= t(kind.to_s.pluralize.downcase) %></a>
              </li>
          <% end %>
          <li class="tab col">
            <a href="#total" <%= 'class=active' if 'total' == params[:kind] %>><%= t(:total) %></a>
          </li>
        </ul>
      </div>

      <!-- Tab panes -->
      <% Visit.kinds.each do |kind, index| %>
          <div class="col s12" id="<%= kind.to_s.pluralize %>">
            <%= render 'visits', relationship: @relationship, kind: kind %>
          </div>
      <% end %>
      <div class="col s12" id="total">
        <%= render 'total', relationship: @relationship %>
      </div>
    </div>
    <script>
        var reload_total_table = false;
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            if ($(e.target).attr('id') == 'total-tab-header' && reload_total_table) {
                $('#total-cont .visits').css('opacity', 0.3);
                $.ajax({
                    url: '<%= total_relationship_path(@relationship) %>',
                    type: 'GET',
                    error: function () {
                    },
                    success: function (res) {
                        $('#total').html(res);
                        $('#total-cont .visits').css('opacity', 1);
                        reload_total_table = false;
                    }
                });
            }
        })
    </script>
<% end %>