config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  get 'archive/index'
  get 'locales/change', as: 'change_locale'

  resources :disciplines
  resources :semesters
  resources :visits, only: [:create, :destroy, :show, :update] do
    resources :homeworks
    member do
      get 'result'
      post 'update_created_at'
    end
  end
  resources :homeworks, only: [:create, :destroy, :show, :update]
  resources :relationships, only: [:create, :destroy, :show] do
    member do
      post 'update_proportions'
      get 'total'
    end
    resources :discipline_modules, only: [:index]
  end
  resources :discipline_modules do
    member do
      get 'generate_tickets'
      post 'do_generate_tickets'
    end
  end
  resources :attends, only: [:create, :update] do
    member do
      post 'update_mark'
      post 'update_title'
    end
  end
  resources :groups do
    member do
      delete 'remove_user'
      post   'add_user'
      get    'search_user'
    end
  end
  resources :student_modules, only: [:show, :destroy] do
    member do
      post 'update_answer_result'
      post 'check_answers'
      get  'finish_check'
      get  'copy_result'
    end
  end

  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users do
    collection do
      post 'create_manual'
    end
  end

  namespace :api do
    namespace :v1 do
      post 'sign_in' => 'users#sign_in'
      get  'relationships/current' => 'relationships#current'
      get  'relationships/:relationship_id/modules' => 'visits#get_modules'
      get  'relationships/:relationship_id/modules/:id' => 'student_modules#show'
      post 'relationships/:relationship_id/modules/:id/questions/:question_id/answer' => 'student_modules#answer'
      post 'relationships/:relationship_id/modules/:id/finish' => 'student_modules#finish'

      get  'disciplines/:discipline_id/modules' => 'discipline_modules#index'
      post 'disciplines/:discipline_id/modules' => 'discipline_modules#create'
      get 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#show'
      post 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#update'
      delete 'disciplines/:discipline_id/modules/:id' => 'discipline_modules#delete'

      get  'modules/:discipline_module_id/question_groups' => 'question_groups#index'
      post 'modules/:discipline_module_id/question_groups' => 'question_groups#create'
      get  'modules/:discipline_module_id/question_groups/:id' => 'question_groups#show'
      post 'modules/:discipline_module_id/question_groups/:id' => 'question_groups#update'
      delete 'modules/:discipline_module_id/question_groups/:id' => 'question_groups#delete'
      
      get  'question_groups/:question_group_id/questions' => 'questions#index'
      post 'question_groups/:question_group_id/questions' => 'questions#create'
      post 'question_groups/:question_group_id/questions/:id' => 'questions#update'
      delete 'question_groups/:question_group_id/questions/:id' => 'questions#delete'

      get  'disciplines' => 'disciplines#index'
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  after_initialize :set_default_status, :if => :new_record?
  before_destroy :check_relationships

  has_many :relationships, dependent: :destroy
  has_many :groupings, :dependent => :destroy
  has_many :users, :through => :groupings

  validates :year, presence: true, numericality: true
  validates :title, presence: true

  default_scope { order 'title'}

  enum status: [:learning, :graduated]

  def set_default_status
    self.status ||= :learning
  end

  def title_year
    title + ' (' + year.to_s + ')'
  end

  def check_relationships
    if relationships.size > 0
      errors.add(:base, 'Cannot delete group. The group studies disciplines: ' + relationships.map {|r| r.discipline.title + ' ('+ r.semester.name + ')'}.join(', ').to_s)
      false
    end
  end

  class << self
    def by_semester(semester)
      where(year: semester.year)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :add_user, :remove_user, :search_user]
  before_action AdminOrTeacherActionCallback

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all.paginate(page: params[:page], per_page: PER_PAGE)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        if !params[:clone_group_id].nil?
          clone_from = Group.find(params[:clone_group_id])
          clone_from.users.each do |user|
            @group.users << user
          end
        end
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    if @group.destroy
      respond_to do |format|
        format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to groups_url, alert: @group.errors.full_messages.join('. ')}
        format.json { render @group.errors }
      end
    end
  end

  def remove_user
    @user = User.find(params[:user_id])
    @group.users.destroy(@user)
    @group.touch
    respond_to do |format|
      format.html { redirect_to @group, notice: 'Student was successfully removed.' }
      format.js
    end
  end

  def add_user
    @user = User.find(params[:user_id])
    if @user.nil?
      redirect_to @group, alert: 'No user was selected'
    else
      if @user.student?
        begin
          @group.users << @user
        rescue ActiveRecord::RecordInvalid => e
          respond_to do |format|
            format.html { redirect_to @group, alert: e.message }
            format.js
          end
        else
          @group.touch
          respond_to do |format|
            format.html { redirect_to @group, notice: 'Student was successfully added.' }
            format.js
          end
        end
      end
    end
  end

  def search_user
    query = params[:q]
    @users = User.student.where('name LIKE ?', "%#{query}%")
    respond_to do |format|
      format.html { redirect_to @group }
      format.json { render json: @users, only: [:id, :name] }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:title, :year)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="row">
  <%= form_for(@group, html: {class: 'form-horizontal col-md-3 col-md-offset-1'}) do |f| %>
      <% if @group.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@group.errors.count, "error") %> <%= t(:group_errors) %>:</h2>

            <ul>
              <% @group.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="row">
        <div class="input-field col s12 m6">
          <%= f.text_field :title, :autofocus => true %>
          <%= f.label t(:title) %>
        </div>
        <div class="input-field col s12 m6">
          <%= f.select :year, 2015..(Time.zone.now.year + 1)%>
          <%= f.label t(:year) %>
        </div>
      </div>

      <%= button_tag t(:create), class: 'btn waves-effect waves-light', type: 'submit' %>

  <% end %>
</div>

app/views/groups/_student_form.html.erb
<%= form_tag(add_user_group_path, class: 'form-inline', id: 'add-student-to-group') do |f| %>
<div class="card hoverable">
  <div class="card-content">
    <span class="card-title black-text"><%= t(:add_student_to_group) %></span>
    <p>
      <%= select_tag 'user_id', {}, {id: 'add_user_id', class: 'browser-default', placeholder: t(:start_typing)} %>
    </p>
  </div>
  <div class="card-action">
    <%= link_to t(:add), '', onclick: '$("#add-student-to-group").submit(); return false;' %>
  </div>
</div>
<% end %>

<%= form_for(Group.new(title: (@group.title.gsub(/\D/, '').to_i+10).to_s, year: @group.year+1)) do |f| %>
    <div class="card hoverable">
      <div class="card-content">
        <span class="card-title black-text"><%= t(:clone_group) %></span>
        <p>
          <%= f.text_field :title %>
          <%= f.number_field :year %>
          <%= hidden_field_tag 'clone_group_id', @group.id %>
        </p>
      </div>
      <div class="card-action">
        <%= link_to t(:create), '', onclick: '$("#new_group").submit(); return false;' %>
      </div>
    </div>
<% end %>

<script type="text/javascript">
    $('#add_user_id').selectize({
        valueField: 'id',
        labelField: 'name',
        searchField: 'name',
        options: [],
        create: false,
        load: function(query, callback) {
            if (query.length < 3) return callback();
            $.ajax({
                url: '<%= search_user_group_path %>',
                type: 'GET',
                dataType: 'json',
                data: {
                    q: query,
                },
                error: function() {
                    callback();
                },
                success: function(res) {
                    callback(res);
                }
            });
        }
    });
</script>

app/views/groups/edit.html.erb
<div class="card hoverable">
  <div class="card-content">
    <span class="card-title black-text"><%= t(:edit) %> <%= t(:group) %></span>
  </div>
</div>

<%= render 'form' %>

<%= link_to t(:show), @group, class: 'btn btn-flat waves-effect waves-teal' %>
<%= link_to t(:back), groups_path, class: 'btn btn-flat waves-effect waves-teal' %>

app/views/groups/index.html.erb
<div class="card hoverable">
  <div class="card-content">
    <span class="card-title black-text"><%= t(:groups) %></span>
    <p>
      <%= link_to t(:new) + ' ' + t(:group), new_group_path, class: 'btn waves-effect waves-light' %>
    </p>
  </div>
</div>

<table class="striped">
  <thead>
  <tr>
    <th><%= t(:title) %></th>
    <th><%= t(:actions) %></th>
  </tr>
  </thead>

  <tbody>
  <% @groups.each do |group| %>
      <tr>
        <td><%= group.title_year %></td>
        <td>
          <%= link_to raw('<i class="fa fa-eye"></i>'), group, title: t(:show) %>
          <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_group_path(group), title: t(:edit) %>
          <%= link_to raw('<i class="fa fa-trash"></i>'), group, method: :delete, data: {confirm: t(:are_you_sure)}, title: t(:delete) %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate %>

app/views/groups/new.html.erb
<div class="card hoverable">
  <div class="card-content">
    <span class="card-title black-text"><%= t(:new) %> <%= t(:group) %></span>
  </div>
</div>

<%= render 'form' %>

<%= link_to t(:back), groups_path, class: 'btn btn-flat waves-effect waves-teal' %>

app/views/groups/show.html.erb
<div class="card hoverable">
  <div class="card-content">
    <span class="card-title black-text"><%= @group.title_year %></span>
  </div>
  <div class="card-action">
    <%= link_to t(:edit), edit_group_path(@group) %>
    <%= link_to t(:back), groups_path %>
  </div>
</div>

<div class="row">
  <div class="col m4 s12">
    <%= render 'student_form'%>
  </div>
  <div class="col m8 s12">
    <ul class="collection with-header">
      <li class="collection-header"><h4><%= t(:students) %></h4></li>
      <% @group.users.order(name: :asc).all.each do |student|%>
          <li class="collection-item">
            <div>
              <%= link_to student.name, student %>
              <%= link_to raw('<i class="material-icons">delete</i>'), remove_user_group_path(user_id: student.id), method: :delete, data: {confirm: t(:are_you_sure) + ' ' + t(:all_marks_will_be_lost)}, class: 'secondary-content', title: t(:delete) %>
            </div>
          </li>
      <% end %>
    </ul>
  </div>
</div>